# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-28 03:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Name')),
                ('description', models.CharField(max_length=50, verbose_name='Description')),
                ('status', models.IntegerField(default=0, verbose_name='Status')),
                ('date_created', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('date_of_enquiry', models.DateField(verbose_name='Date of Enquiry')),
            ],
            options={
                'verbose_name': 'Seed',
                'verbose_name_plural': 'Seeds',
            },
        ),
        migrations.CreateModel(
            name='SeedCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('code', models.CharField(max_length=20, verbose_name='Code')),
            ],
            options={
                'verbose_name': 'Seed Company',
                'verbose_name_plural': 'Seed Companies',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Authenticator.SeedCompany'),
        ),
    ]
